### ISSUE TITLE
[BUG] Grub boot stanza doesn't exclude floppy. Could result in grub hangs.

### ISSUE THREAD

**Issue by alexdepalex** [harvester/harvester#2115]
**Describe the bug**
Grub boot stanza doesn't exclude floppy (--no-floppy). In situations where disks are reshuffled or multiple controller setups, this might result in non-existing floppy drives to be scanned, which blocks the boot cycle, or dropping to grub rescue prompt for 30 minutes.

**To Reproduce**
1. Have an awkward disk configuration or make the partition containing the boot label vanish.

**Expected behavior**
Don't scan for floppy's.

**Support bundle**

**Environment:**
 - Harvester ISO version:  1.0.1-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
 Dell RX740d with iDrac 5.10.10.00

**Additional context**
We're trying to install Harvester on sdb, which seems to be causing issues as well.

**Comment by alexdepalex** [comment]
Seems like cOS isn't using the `--no-floppy` flag when install grub2.

https://github.com/rancher-sandbox/cOS-toolkit/blob/master/packages/backports/installer/cos.sh#L648

**Comment by Itxaka** [comment]
AFAIK the `--no-floppy` stanza is not used during grub install but during search instead, so we should change the search stuff in the grub config: https://www.gnu.org/software/grub/manual/grub/grub.html#search

**Comment by Itxaka** [comment]
This may be possible to fix on harverster directly by setting the stanza on your grub config: https://github.com/harvester/harvester-installer/blob/master/package/harvester-os/iso/boot/grub2/grub.cfg#L1

**Comment by Itxaka** [comment]
Im not sure if we expect anyone to store the kernel on a floppy, so maybe we should just disable it on cos directly if there is not much to gain...

**Comment by alexdepalex** [comment]
I think this is the template that's used for creating the `grub.cfg`, so it probably needs to be added there.

https://github.com/rancher-sandbox/cOS-toolkit/blob/master/packages/grub2/config/grub.cfg.tmpl

**Comment by Itxaka** [comment]
yep, was looking for that...that may be handy if someone wants to add some env files from a floppy...it would be weird but they might use floppy in 2022 I guess lol

**Comment by alexdepalex** [comment]
I'd say, just disable it. I don't think running Harvester from floppies is an actual use case that they're willing to support.

**Comment by mudler** [comment]
Yes I do agree disabling it makes sense. Note that the config in https://github.com/rancher-sandbox/cOS-toolkit/blob/master/packages/grub2/config/grub.cfg.tmpl applies to a running environment and not to the ISO in case of harvester. This is because https://github.com/harvester/harvester-installer/blob/master/package/harvester-os/iso/boot/grub2/grub.cfg#L1 overrides the cOS defaults

**Comment by Itxaka** [comment]
PR: https://github.com/rancher-sandbox/cOS-toolkit/pull/1220
Also as mentioned by Ettore, this also requires changes in the harvester-installer grub.cfg that overrides the base cos one.

Poor floppies, wont somebody think of them anymore :crying_cat_face:

**Comment by Itxaka** [comment]
Fix was merged on cos-toolkit, new packages should be published in the repos in a couple of hours max! https://github.com/rancher-sandbox/cOS-toolkit/actions/runs/2108139563

**Comment by alexdepalex** [comment]
Cool. If it's included in the Harvester nightly, I can give it a shot tomorrow.

**Comment by guangbochen** [comment]
@alexdepalex can u please help to do a quick validation against the latest [v1.0.1-rc3 release](https://github.com/harvester/harvester/releases/tag/v1.0.1-rc3), thanks in advance.

**Comment by alexdepalex** [comment]
Yes. Will do within an hour or 2.

**Comment by alexdepalex** [comment]
At first glance it doesn't seem to fix our issue. I need to wait half an hour before grub proceeds.

**Comment by Itxaka** [comment]
@alexdepalex any logs? Do we have a link to the iso with the patch to test locally?

**Comment by Itxaka** [comment]
oh, I see the link just above :D

**Comment by Itxaka** [comment]
@alexdepalex when you refer to `Have an awkward disk configuration or make the partition containing the boot label vanish.` what do you mean exactly, what type of devices do I need in a VM to reproduce this?

**Comment by weihanglo** [comment]
@Itxaka 
Just FYI, for v1.0.01-rc3 we haven't got a time to upgrade cOS-toolkit. Instead, we patched it manually https://github.com/harvester/harvester-installer/pull/266

**Comment by Itxaka** [comment]
@weihanglo yup, saw it but the patch is basically the same (including the problem with the --set=root :P) so it should validate the same I hope.

**Comment by alexdepalex** [comment]
> @alexdepalex any logs? Do we have a link to the iso with the patch to test locally?

I'm doing a redeploy right now. Will try to get the logs from the installer. Are these logs also available on the node after reboot?

**Comment by Itxaka** [comment]
nope, but Im more interested in the grub logs if its being stuck int here, so you should try to capture the serial output, not sure if possible on that dell server, thats why I wanted to try to reproduce it in a VM, serial logs are easy that way :D

**Comment by alexdepalex** [comment]
The serial output doesn't show anything additional that's not on the console. Shouldn't `grub2-install` be executed with the `--no-floppy` flag as well?

**Comment by Itxaka** [comment]
As far as I know `grub2-install` does not have a `--no-floppy` flag? 

https://www.gnu.org/software/grub/manual/grub/html_node/Installing-GRUB-using-grub_002dinstall.html

```
Usage: grub2-install [OPTION...] [OPTION] [INSTALL_DEVICE]
Install GRUB on your drive.

      --compress=no|xz|gz|lzo   compress GRUB files [optional]
      --disable-shim-lock    disable shim_lock verifier
      --dtb=FILE             embed a specific DTB
  -d, --directory=DIR        use images and modules under DIR
                             [default=/usr/share/grub2/<platform>]
      --fonts=FONTS          install FONTS [default=unicode]
      --install-modules=MODULES   install only MODULES and their dependencies
                             [default=all]
  -k, --pubkey=FILE          embed FILE as public key for signature checking
      --locale-directory=DIR use translations under DIR
                             [default=/usr/share/locale]
      --locales=LOCALES      install only LOCALES [default=all]
      --modules=MODULES      pre-load specified modules MODULES
      --sbat=FILE            SBAT metadata
      --themes=THEMES        install THEMES [default=starfield]
  -v, --verbose              print verbose messages.
      --allow-floppy         make the drive also bootable as floppy (default
                             for fdX devices). May break on some BIOSes.
      --boot-directory=DIR   install GRUB images under the directory DIR/grub2
                             instead of the boot/grub2 directory
      --bootloader-id=ID     the ID of bootloader. This option is only
                             available on EFI and Macs.
      --core-compress=xz|none|auto
                             choose the compression to use for core image
      --disk-module=MODULE   disk module to use (biosdisk or native). This
                             option is only available on BIOS target.
      --efi-directory=DIR    use DIR as the EFI System Partition root.
      --force                install even if problems are detected
      --force-file-id        use identifier file even if UUID is available
      --label-bgcolor=COLOR  use COLOR for label background
      --label-color=COLOR    use COLOR for label
      --label-font=FILE      use FILE as font for label
      --macppc-directory=DIR use DIR for PPC MAC install.
      --no-bootsector        do not install bootsector
      --no-nvram             don't update the `boot-device'/`Boot*' NVRAM
                             variables. This option is only available on EFI
                             and IEEE1275 targets.
      --no-rs-codes          Do not apply any reed-solomon codes when
                             embedding core.img. This option is only available
                             on x86 BIOS targets.
      --product-version=STRING   use STRING as product version
      --recheck              delete device map if it already exists
      --removable            the installation device is removable. This option
                             is only available on EFI.
  -s, --skip-fs-probe        do not probe for filesystems in DEVICE
      --suse-enable-tpm      install TPM modules
      --suse-force-signed    force installation of signed grub.This option is
                             only available on ARM64 EFI targets.
      --suse-inhibit-signed  inhibit installation of signed grub. This option
                             is only available on ARM64 EFI targets.
      --target=TARGET        install GRUB for TARGET platform
                             [default=i386-pc]; available targets:
                             arm-coreboot, arm-efi, arm-uboot, arm64-efi,
                             i386-coreboot, i386-efi, i386-ieee1275,
                             i386-multiboot, i386-pc, i386-qemu, i386-xen,
                             i386-xen_pvh, ia64-efi, mips-arc, mips-qemu_mips,
                             mipsel-arc, mipsel-loongson, mipsel-qemu_mips,
                             powerpc-ieee1275, riscv32-efi, riscv64-efi,
                             s390x-emu, sparc64-ieee1275, x86_64-efi,
                             x86_64-xen
      --zipl-directory=DIR   use DIR as the zIPL Boot Partition root.
  -?, --help                 give this help list
      --usage                give a short usage message
  -V, --version              print program version

Mandatory or optional arguments to long options are also mandatory or optional
for any corresponding short options.

INSTALL_DEVICE must be system device filename.
grub2-install copies GRUB images into boot/grub2.  On some platforms, it may
also install GRUB into the boot sector.

Report bugs to <bug-grub@gnu.org>.
```

**Comment by alexdepalex** [comment]
It's a hidden option for whatever reason.

https://github.com/rhboot/grub2/blob/master/util/grub-install.c#L289

**Comment by alexdepalex** [comment]
Ah, seems to be for compatibility.

**Comment by Itxaka** [comment]
yep, just saw it, it doesnt seem to do anything at all :/

**Comment by Itxaka** [comment]
@alexdepalex can you maybe drop to the grub shell (press c in the grub menu) and run the search commands manually to see if its indeed that what is slowing down the boot? Maybe the issue is a different one and we are working on the wrong stuff

**Comment by guangbochen** [comment]
~~It is hard to be reproduced on our local or KVM env, wondering if we can have some stable reproduction steps using a KVM?~~

We are considering moving this one to the v1.0.2 release (targetting on 10th May), let us know if u guys have additional concerns, thanks.

**Comment by alexdepalex** [comment]
> @alexdepalex can you maybe drop to the grub shell (press c in the grub menu) and run the search commands manually to see if its indeed that what is slowing down the boot? Maybe the issue is a different one and we are working on the wrong stuff

So this occurs before the grub config is actually loaded. If I drop to a shell after that and try to `ls`  the devices, it hangs again. After some time it proceeds and print 2 floppy drives.

**Comment by bk201** [comment]
From the current investigation, the causes might be:
- GRUB is stuck when scanning VirtualCD device (even the device is disabled)
- related to specific fw version of Dell BOSS-S1 adapter. A supportconfig data could help.

**Comment by ravarga** [comment]
Issue is related to a specific firmware of Dell BOSS adapter (3022). Downgrading firmware solves the problem

**Comment by bk201** [comment]
Check if we can revert https://github.com/harvester/harvester-installer/pull/279

*Update*: need to wait for https://github.com/harvester/harvester/issues/2565 to remove the workaround

**Comment by TachunLin** [comment]
Verified **not fixed** on `master-b0d883ce-head`. Move the issue to implement. 

### Result
In new ISO installation of Harvester, we can complete the installation process and the the file `/oem/grubenv` **exists** 

But when we upgrade from v1.0.3 and v1.1.0 to v1.1.1 master, the `/oem/grubenv` **did not exists** after the upgrade 
Thus suggest we could have an enhancement for upgrade scenarios. 


### New v1.1.1 master installation
Use ISO installation with floppy device attached on VM. 

* Can complete new Harvester using ISO installation and boots up normally.
  ![image](https://user-images.githubusercontent.com/29251855/203707323-51a28188-fa9b-4318-8c89-1172631587d0.png)


* Check the path /oem/grubenv. The file exists.
  - Multi-nodes
  ```
  harvester-node-0:~ # ls /oem/grubenv
  /oem/grubenv
  ```
  - Single-node
  ```
  harv1122:~ # ls /oem/grubenv
  /oem/grubenv
  ```

### Upgrade from v1.0.3 to v.1.1.1 master
* Can't find the file /oem/grubenv after upgrade 
  ```
  harvester-node-0:~ # ls /oem/grubenv
  ls: cannot access '/oem/grubenv': No such file or directory
  ```

### Upgrade from v1.1.0 to v.1.1.1 master 
* Can't find the file /oem/grubenv after upgrade 
  ```
  harv110:~ # ls /oem/grubenv 
  ls: cannot access '/oem/grubenv': No such file or directory
  ```

### Test Information
* Test Environment: 4 nodes Harvester bare machines
* Harvester version: master-0f590757-head

### Verify Steps
1. Prepare a VM and add a floppy device 
![image](https://user-images.githubusercontent.com/29251855/203779493-719d3701-1b64-4c31-83e1-0acb594c14e5.png)

2. ISO install v1.1.1 master release
  ![image](https://user-images.githubusercontent.com/29251855/203704481-662bbcf6-9ae7-43f3-992e-9f70adfd7e77.png)

3. Complete the installation and Harvester can come up 
4. ssh to management node 
5. Check file `/oem/grubenv` exists.
6. Prepare a v1.0.3 and v1.1.0 Harvester cluster 
7. Upgrade to v1.1.1 master 
8. Check step 5

**Comment by TachunLin** [comment]
Verified **fixed** on `master-223d3bf9-head`. Close this issue. 

### Result
* In new ISO installation of Harvester, we can complete the installation process and the the file `/oem/grubenv` **exists** 
* When we upgrade from v1.0.3 and v1.1.0 to v1.1.1 master, the `/oem/grubenv` **exists** after the upgrade 

### New v1.1.1 master installation
* Can complete new Harvester using ISO installation and boots up normally.
![image](https://user-images.githubusercontent.com/29251855/204007571-d252cd12-89c5-421b-a80a-b7cc374c7c0b.png)

* Check the path `/oem/grubenv`. The file exists.
  ```
  rancher@harv1125:~> ls /oem/grubenv
  /oem/grubenv
  ```

### Upgrade from v1.0.3 to v.1.1.1 master
* Check the path `/oem/grubenv`. The file exists.
  ```
  rancher@harv103upd:~> ls /oem/grubenv
  /oem/grubenv
  ```

### Upgrade from v1.1.0 to v.1.1.1 master 
* Check the path `/oem/grubenv`. The file exists.
  ```
  rancher@harvester-node-0:~> ls /oem/grubenv
  /oem/grubenv
  ```

### Test Information
* Test Environment: 4 nodes and 1 node kvm machine
* Harvester version: `master-223d3bf9-head` (11/25)

### Verify Steps
https://github.com/harvester/harvester/issues/2115#issuecomment-1326366093
