### ISSUE TITLE
[BUG]  show Harvester cluster in Continuous Delivery Clusters page

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#4482]
**Describe the bug**

Turn on `harvester-baremetal-container-workload `, harvester clusters are not shown in the Continuous Delivery Clusters page

**To Reproduce**
1. import a harvester
2. go to setting
3. click `Feature` Flags,   Enable `harvester-baremetal-container-workload`
4. go to `Continuous Delivery`,  Click `Clusters` Tab

**Expected behavior**

You should see the Harvester cluster in the Rancher's **Continous Delivery** support page.

Expected supported Rancher version: v2.8 and backported to the most recent v2.7 release.
- [x] rancher 2.8.0
- [x] rancher 2.7.X

**Support bundle**

**Environment**
 - Harvester ISO version:   harvester v1.2.0-rc6
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by bk201** [comment]
@torchiaf Can you help check if we can move to ready for testing and confirm we have this in v1.3.0+. Thanks.

**Comment by torchiaf** [comment]
@bk201 This is fixed in Rancher code-base, version 2.8. I think we could create the 2.7 backport.

**Comment by bk201** [comment]
I removed v1.2/v1.3 backport issues since it's coupled with Rancher releases.

**Comment by torchiaf** [comment]
Related Rancher PR https://github.com/rancher/dashboard/pull/10951

**Comment by TachunLin** [comment]
Verified **not fixed** on `master-0fa939f-head` (24/08/13) with Rancher `v2.8.5` and `v2.7.10`.  Move this issue to implement

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ On Rancher v2.8.5, we can see the Harvester cluster in the Continuous Delivery page $~~$</summary>

1. After enable the harvester-baremetal-container-workload, we can see the Harvester cluster in the Continuous Delivery page

  ![image](https://github.com/user-attachments/assets/4e0df0e1-8375-468a-87cd-7b87608b81c3)


 </details>

<details><summary>$\color{red}{\textsf{Failed}}$ On Rancher v2.7.10, we <strong>can't see</strong> the Harvester cluster in the Continuous Delivery page $~~$</summary>

1. After enable the harvester-baremetal-container-workload, we <strong>can't</strong>  see the Harvester cluster in the Continuous Delivery page

  ![image](https://github.com/user-attachments/assets/f62ad88d-7f8a-41de-84a0-bbcdd2db5c48)


 </details>

### Test Information
* Test Environment: Single nodes harvester on local and remote kvm machines
* Harvester version: `master-0fa939f-head` (24/08/13)

### Verify Steps
<details><summary> Check Harvester cluster in Continuous Delivery page </summary>

1. import a harvester
2. go to setting
3. click `Feature Flags`, Enable the `harvester-baremetal-container-workload`
  ![image](https://github.com/user-attachments/assets/b26c3f31-35e2-43eb-b2a1-fc13095ceb3c)
4. go to `Continuous Delivery`, Click `Clusters` Tab

</details>

**Comment by TachunLin** [comment]
@torchiaf ,

We found on Rancher `v2.7.10` with latest Harvester master release. 
After enabled the `harvester-baremetal-container-workload`, we still can't see the Harvester in Continuous Delivery clusters page. 

![image](https://github.com/user-attachments/assets/0db37393-36e9-4906-8a97-123f78c1c76b)

May I know whether it would be the expected result or we have the plan to include this fix also on Rancher `v2.7.x` release. Thank you.

**Comment by torchiaf** [comment]
> May I know whether it would be the expected result or we have the plan to include this fix also on Rancher `v2.7.x` release. Thank you.

The issue is fixed in Rancher `v2.7.13` and higher.

**Comment by TachunLin** [comment]
Retest **PASS** on Rancher `v2.7.13` with Harvester master-0e15f01-head (24/09/18). Close this issue.

After enable the harvester-baremetal-container-workload, we **can** see the Harvester cluster in the Continuous Delivery page

![image](https://github.com/user-attachments/assets/04f4fa8d-29e6-40d4-911a-5988ab24417c)
